language: python
env:
  #- DJANGO=1.4 GDAL=1.10 DB=sqlite
  - DJANGO=1.5 GDAL=1.10 DB=sqlite
  #- DJANGO=1.6 GDAL=1.10 DB=sqlite
python:
  #- "2.6"
  - "2.7"
  #- "pypy"
virtualenv:
  system_site_packages: true
before_install:
  # adding required repo for dependencies
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install aptitude
  # install a lot of deps from the apt-repos
  - sudo aptitude install -y gdal-bin libgdal1-dev libxml2 python-lxml python-libxml2 libproj0 libproj-dev libgeos-dev libgeos++-dev cgi-mapserver python-mapscript python-psycopg2 postgis python-gdal
install:
  # test with various Django versions
  - pip install -q Django==$DJANGO
  # test with various GDAL versions
  #- pip install -q gdal==$GDAL --use-mirrors
  # actually install EOxServer
  - pip install --install-option="--disable-extended-reftools" .
script:
  #- 'if ["$DB" == "postgis"]; then sudo -u postgres createdb eoxserver_demo; fi'
  #- 'if ["$DB" == "postgis"]; sudo -u postgres psql eoxserver_demo -c ''create extension postgis;''; fi'
  - python -c "from osgeo import gdal; print dir(gdal)"
  - cd autotest
  - python manage.py test core
  - python manage.py test backends
  - python manage.py test coverages
  - python manage.py test autotest_services
notifications:
  irc:
    channels:
      - "irc.freenode.net#eoxserver"
    on_success: always
    on_failure: always
