language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install ."
script:
  - cd autotest
  - python manage.py test core
  - python manage.py test backends
  - python manage.py test coverages
  - python manage.py test autotest_services
