language: python
python:
  - "2.6"
  - "2.7"
install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install gdal python-gdal libgdal1-dev
  - "pip install ."
script:
  - cd autotest
  - python manage.py test core
  - python manage.py test backends
  - python manage.py test coverages
  - python manage.py test autotest_services
